@SecureVault.Api_HostAddress = https://localhost:7091
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOTk2ZWYzOS0zMGRiLTQ5MTgtOGNmNy0zNDVjNDY3NTg0MGYiLCJ1bmlxdWVfbmFtZSI6InRlc3RVc2VyIiwianRpIjoiZjdhMDVmY2ItMWI2Ny00Y2RhLTg2MjAtOGFkZDE3MjZmNGYyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc3ODYwMTM4NSwiaXNzIjoiU2VjdXJlVmF1bHQuQXBpIiwiYXVkIjoiU2VjdXJlVmF1bHQuQXBpQXVkaWVuY2UifQ.kInXFfNp2Tqb70KW04wbeBDlU5l2LNUg_M8Z_-zylmg
@refreshToken = b2b3d166-7e9a-4540-98f7-250e71026a8e

POST {{SecureVault.Api_HostAddress}}/register
Content-Type: application/json

{
  "userName": "testGuestUser",
  "password": "testGuest@1234"  
}

### Register an admin user. Requieres SuperAdmin Role.

POST {{SecureVault.Api_HostAddress}}/register-admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userName": "testAdminUser",
  "password": "testAdmin@1234",
  "role": "Admin"
}

###

POST {{SecureVault.Api_HostAddress}}/register
Content-Type: application/json

{
  "userName": "testUser",
  "password": "testUser@1234",
  "role": "User"
}

###

POST {{SecureVault.Api_HostAddress}}/login
Content-Type: application/json

{
  "userName": "superadmin",
  "password": "superAdmin123_!!"
}

###

POST {{SecureVault.Api_HostAddress}}/login
Content-Type: application/json

{
  "userName": "testAdminUser",
  "password": "testAdmin@1234"
}

###

POST {{SecureVault.Api_HostAddress}}/login
Content-Type: application/json

{
  "userName": "testUser",
  "password": "testUser@1234"
}

###

POST {{SecureVault.Api_HostAddress}}/login
Content-Type: application/json

{
  "userName": "testGuestUser",
  "password": "testGuest@1234"
}

###

GET {{SecureVault.Api_HostAddress}}/protected
Authorization: Bearer {{accessToken}}


###

GET {{SecureVault.Api_HostAddress}}/admin-role
Authorization: Bearer {{accessToken}}

###

POST {{SecureVault.Api_HostAddress}}/refresh
Content-Type: application/json

{
  "RefreshToken": "{{refreshToken}}"
}