@SecureVault.Api_HostAddress = https://localhost:7091
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMzU1ZGUwZC1mOGYyLTQ3YzQtYjY0Ny1kN2ZlMTEzMDkwNTciLCJ1bmlxdWVfbmFtZSI6InN1cGVyYWRtaW4iLCJqdGkiOiIwNzg1YTUxZS04YzhkLTQ5ZGUtOWI0NC1jMzZiNTJlNDAwOWUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdXBlckFkbWluIiwiZXhwIjoxNzc4ODYwOTcxLCJpc3MiOiJTZWN1cmVWYXVsdC5BcGkiLCJhdWQiOiJTZWN1cmVWYXVsdC5BcGlBdWRpZW5jZSJ9.tmp-OQdA28kTfIu1Yka4DStbtMvHoz_hHBhBZOsYLg8
@refreshToken = b2b3d166-7e9a-4540-98f7-250e71026a8e


### Register an user without role, should fail.
POST {{SecureVault.Api_HostAddress}}/register
Content-Type: application/json

{
  "userName": "testGuestUser",
  "password": "testGuest@1234"  
}


### Register an user with User role
### Should pass, unless the username is taken.
POST {{SecureVault.Api_HostAddress}}/register
Content-Type: application/json

{
  "userName": "testUser",
  "password": "testUser@1234",
  "role": "User"
}

### Test new User user created.
### Should pass if the above POST request passed.

POST {{SecureVault.Api_HostAddress}}/login
Content-Type: application/json

{
  "userName": "testUser",
  "password": "testUser@1234"
}

### Login as SuperAdmin and generate jwt
POST {{SecureVault.Api_HostAddress}}/login
Content-Type: application/json

{
  "userName": "superadmin",
  "password": "superAdmin123_!!"
}


### Register an admin user.
### Should pass if there's an user with SuperAdmin Role logged in and the username is not taken.
POST {{SecureVault.Api_HostAddress}}/register-admin
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userName": "testAdminUser",
  "password": "testAdmin@1234",
  "role": "Admin"
}


### Test new Admin user created.
### Should pass if the above POST request passed.
POST {{SecureVault.Api_HostAddress}}/login
Content-Type: application/json

{
  "userName": "testAdminUser",
  "password": "testAdmin@1234"
}


###
POST {{SecureVault.Api_HostAddress}}/login
Content-Type: application/json

{
  "userName": "newAdmin",
  "password": "testAdmin@1234"
}


###

POST {{SecureVault.Api_HostAddress}}/login
Content-Type: application/json

{
  "userName": "testGuestUser",
  "password": "testGuest@1234"
}

###

GET {{SecureVault.Api_HostAddress}}/protected
Authorization: Bearer {{accessToken}}


###

GET {{SecureVault.Api_HostAddress}}/admin-role
Authorization: Bearer {{accessToken}}

###

POST {{SecureVault.Api_HostAddress}}/refresh
Content-Type: application/json

{
  "RefreshToken": "{{refreshToken}}"
}


###
GET {{SecureVault.Api_HostAddress}}/userinfo
Authorization: Bearer {{accessToken}}


###